---
- name: restart mysql
  become: true
  community.general.docker_container:
    working_dir: /var/wordpress
    name: mysql
    auto_remove: no
    restart: yes
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    image: mysql:5.7
    volumes:
     - /var/wordpress/mysql/db:/var/lib/mysql
     - /var/wordpress/mysql/files:/etc/mysql
    env:
     MYSQL_ROOT_PASSWORD: wordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress