---
- name: Prepare host
  hosts: all
  tasks:
  - name: Install a list of packages
    become: true
    apt:
      update_cache: yes
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - curl
      - gnupg2
      - lsb-release
    tags:
      - deployhost
  - name: Install docker python package
    become: true
    command: pip3 install docker
    tags:
      - deployhost
  - name: Import docker gpg key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - deployhost
  - name: Add docker repo
    become: true
    command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    tags:
      - deployhost  
  - name: Install docker
    become: true
    apt:
      update_cache: yes
      force_apt_get: yes
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    tags:
      - deployhost
  - name: Set python 3 as default
    become: true
    command: update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    tags:
      - deployhost
  - name: Create internal network for app
    become: true
    community.general.docker_network:
      name: backend
      internal: yes
    tags:
      - deployapp
  - name: Create public network for app
    become: true
    community.general.docker_network:
      name: fronetnd
    tags:
      - deployapp
  - name: Creates data grafana directory
    become: true
    file:
      path: /var/grafana/data
      state: directory
      mode: 0775
    tags:
      - deployhost
  - name: Restore grafana
    become: true
    copy:
      src: grafana.db
      dest: /var/grafana/data/grafana.db
      mode: 0775
    tags:
      - deployhost
- name: Wordpress Blog
  become: true
  hosts: wordpress
  roles:
    - db
    - wordpress
    - nginx_wordpress
  tags:
    - deployapp

- name: Monitoring
  become: true
  hosts: wordpress
  roles:
    - cadvisor
    - nodeexporter
    - prometheus
    - grafana
    - nginx_grafana
    - render
  tags:
    - deploymonitoring